{
 "title": "mlops-view-222.json",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Fraud predictions (counter)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fraud_predictions_total\r\n", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Requests per second (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(requests_total[1m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency p95 (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(request_latency_seconds_bucket[5m])) by (le))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "split RPS by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (endpoint) (rate(requests_total[1m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fraud rate (% over time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "100 * sum(rate(fraud_predictions_total[5m])) / clamp_min(sum(rate(predictions_total[5m])), 1e-9)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "100 * sum(rate(errors_total[5m])) / clamp_min(sum(rate(requests_total[5m])), 1e-9)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Predictions",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "predictions_total\r\n", "legendFormat": "__auto" }
   ]
  }
 ]
}